import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>OEV UI Dev Test</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <p>
                    Nothing to see here. Run <code>yarn storybook</code> to
                    complete the technical task
                </p>
            </main>
        </>
    );
}
